name = "RFFingerprint_Models"
uuid = "9896bf05-9493-4e5b-be64-41b6a423b7e2"
authors = ["Robin Gerzaguet <robin.gerzaguet@irisa.fr> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
